# Generated by Django 3.2.8 on 2021-11-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='article_images'),
        ),
    ]
